name: event_alert
description: A Flutter package project for handling alerts using event_bloc.
version: 0.1.3
homepage: https://github.com/VHCBlade/event_alert

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  event_bloc: ^4.7.0

  flutter:
    sdk: flutter

dev_dependencies:
  event_bloc_tester: ^0.1.4

  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
